import { appAccountBoxIcon } from './account_box';
import { appCheckCircleIcon } from './check_circle';
import { appExpandIcon } from './expand';
import { appFavoriteIcon } from './favorite';
import { appHomeIcon } from './home';
import { appLogoutIcon } from './logout';
import { appRedeemIcon } from './redeem';
import { appSearchIcon } from './search';
import { appSettingsIcon } from './settings';
export const actionIcons = [appAccountBoxIcon, appCheckCircleIcon, appExpandIcon, appFavoriteIcon, appHomeIcon, appLogoutIcon, appRedeemIcon, appSearchIcon, appSettingsIcon];
